title: Your Name
author: Your Name
email: your-email@example.com
url: https://babskhalidson.com

remote_theme: chesterhow/tale

permalink: /:year-:month-:day/:title
paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Optional: Disqus comments (change to your Disqus shortname or remove)
# disqus: your-disqus-shortname

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
